name: Deploy to control.waterai.cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Wgraj pliki na serwer (SFTP)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: waterai.cloud
          port: 22
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './*'
          remote_path: './'
          sftp_only: true
